services:
  paymybuddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paymybuddy
    restart: always
    depends_on:
      - paymybuddydb
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - paymybuddy_network

  paymybuddydb:
    image: mysql:latest
    container_name: paymybuddydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cisko
      MYSQL_PASSWORD: password
    volumes:
      - db_paymybuddy:/var/lib/mysql 
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - paymybuddy_network

volumes:
  db_paymybuddy:

networks:
  paymybuddy_network:

    
